config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'

  namespace :api do
    resources :books, only: %i[show]
  end

  resources :books
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
end

app/controllers/api/base_controller.rb
# frozen_string_literal: true

class API::BaseController < ApplicationController
end

app/controllers/api/books_controller.rb
# frozen_string_literal: true

class API::BooksController < API::BaseController
  def show
    @book = Book.find(params[:id])
    render json: @book
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @books = Book.order(:id)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    book.save!
    redirect_to books_path, notice: "#{book.title} has been successfully created!"
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update!(book_params)
    redirect_to books_path, notice: "#{book.title} has been successfully updated!"
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "#{book.title} has been successfully deleted٩( 'ω' )و"
  end

  private

  def book_params
    params.require(:book).permit(:title, :memo, :paper)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_form.html.slim
= form_with model: book, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :memo
    = f.text_area :memo, rows:5, class: 'form-control'
  .form-group
    = f.label :paper
    = f.check_box :paper, {}, true, false
  = f.submit nil, class: 'btn btn-primary'

app/views/books/edit.html.slim
h1 Edit Book

.nav.justify-content-end
  = link_to 'list', books_path, class: 'nav-link'

#js-edit-form(data-book-id="#{@book.id}")

app/views/books/index.html.slim
h1 Book List

= link_to 'create', new_book_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
     th= 'Title'
     th= 'Created at'
     th
  tbody
    - @books.each do |book|
      tr
        td= link_to book.title, book_path(book)
        td= book.created_at
        td
          = link_to 'edit', edit_book_path(book), class: 'btn btn-primary mr-3'

app/views/books/new.html.slim
h1 New Book

.nav.justify-content-end
  = link_to 'list', books_path, class: 'nav-link'

#js-new-form

app/views/books/show.html.slim
h1 Book Details

.nav.justify-content-end
  = link_to 'list', books_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= 'Title'
      td= @book.title
    tr
      th= 'Memo'
      td= simple_format(h(@book.memo), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= 'Digital or Paper'
      td= @book.paper ? 'Paper' : 'Digital'
    tr
      th= 'Created at'
      td= @book.created_at
    tr
      th= 'Updated at'
      td= @book.updated_at

= link_to 'edit', edit_book_path, class: 'btn btn-primary mr-3'
= link_to 'delete', @book, method: :delete, data: { confirm: "Are you sure you want to delete #{@book.title}?"}, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TechBooks
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
  body
    = yield